site_name: Cobra
pages:
- Getting Started:
  - Introduction: 'introduction.md'
  - Installation: 'installation.md'
  - Configuration: 'configuration.md'
- Usage:
  - GUI: 'GUI.md'
  - CLI: 'CLI.md'
  - API: 'API.md'
- Structure:
  - Framework: 'framework.md'
  - Tables: 'tables.md'
- Resources:
  - Rule List: 'rule_list.md'
  - Vulnerabilities: 'vulnerabilities.md'
  - Languages: 'languages.md'
- Modules:
  - Detection URI: 'detection_uri.md'
- FAQ: 'FAQ.md'
- Reference:
  - Rule Source: 'rule_source.md'

theme: readthedocs